  language: python
  dist: xenial   # required for Python >= 3.7
  python:
    - "3.7"
  before_install:
    - "pip install -U pip"
    - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  install:
    - pip install -r requirements.txt
  script: python Test/TestAlgoritmi.py


